import CryptoKit
import XCTest
@testable import SwarmCore

/// Qualifies the Swift chat crypto against the vectors Android's ChatProtocolTest uses
/// (generated by the TypeScript client): same file, same expectations.
final class ChatVectorsTests: XCTestCase {
    private var v: [String: Any] = [:]
    override func setUpWithError() throws {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().appendingPathComponent("android/app/src/test/resources/chat-vectors.json")
        v = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
    }
    private func obj(_ o: Any?, _ path: String...) -> [String: Any] {
        path.reduce(o as? [String: Any] ?? [:]) { ($0[$1] as? [String: Any]) ?? [:] }
    }

    func testReplyForwardAndDeleteForEveryonePayloads() throws {
        let id = "7d0b4c0e-3c8b-4c1e-9a43-0b0f6b1f2f11"
        try ChatRules.payload(["text": "Yes", "replyTo": id, "forwarded": true], format: "TEXT")
        try ChatRules.payload(["deletes": id], format: "SYSTEM")
        XCTAssertThrowsError(try ChatRules.payload(["deletes": id], format: "TEXT"))
        XCTAssertThrowsError(try ChatRules.payload(["deletes": id, "text": "x"], format: "SYSTEM"))
        XCTAssertThrowsError(try ChatRules.payload(["text": "x", "replyTo": "not-a-uuid"]))
        XCTAssertThrowsError(try ChatRules.payload(["text": "x", "forwarded": false]))
        XCTAssertThrowsError(try ChatRules.payload(["text": "x", "forwarded": 1]))
    }

    func testProfilesSignaturesAndIdentitiesMatchTheOtherClients() throws {
        let dm = obj(v, "dm"), body = obj(dm, "body"), author = obj(body, "author")
        let key = obj(author, "body", "publicKey")
        XCTAssertTrue(try ChatCrypto.verify(author, publicKey: key), "profile signature")
        XCTAssertEqual(try ChatCrypto.participantID(key), obj(author, "body")["id"] as? String)
        XCTAssertTrue(try ChatCrypto.verify(dm, publicKey: key), "DM envelope signature over canonical JSON")
        var forged = author
        var forgedBody = obj(author, "body"); forgedBody["name"] = "Impersonator"; forged["body"] = forgedBody
        XCTAssertFalse(try ChatCrypto.verify(forged, publicKey: key))
        let me = try XCTUnwrap(body["recipientId"] as? String), them = try ChatCrypto.participantID(key)
        XCTAssertEqual(try ChatCrypto.directConversationID(me, them), body["conversationId"] as? String)
    }

    func testDirectMessageDecryptsOnlyInItsContext() throws {
        let body = obj(v, "dm", "body"), privateKey = obj(v, "recipientPrivateJwk")
        let content = try XCTUnwrap(body["content"] as? String)
        let kid = "dm:\(body["conversationId"]!):\(body["id"]!):\(body["recipientId"]!)"
        XCTAssertEqual(try ChatCrypto.decrypt(content, privateKey: privateKey, kid: kid)["text"] as? String, "Where is Gate 2?")
        XCTAssertThrowsError(try ChatCrypto.decrypt(content, privateKey: privateKey, kid: kid + "x"), "wrong context")
        var parts = content.split(separator: ".").map(String.init)
        parts[3] = (parts[3].first == "A" ? "B" : "A") + parts[3].dropFirst()
        XCTAssertThrowsError(try ChatCrypto.decrypt(parts.joined(separator: "."), privateKey: privateKey, kid: kid), "tampered")
        let other = P256.KeyAgreement.PrivateKey()
        let x963 = other.publicKey.x963Representation
        let wrong: [String: Any] = ["kty": "EC", "crv": "P-256", "x": ChatCrypto.base64url(x963[1..<33]),
                                    "y": ChatCrypto.base64url(x963[33..<65]), "d": ChatCrypto.base64url(other.rawRepresentation)]
        XCTAssertThrowsError(try ChatCrypto.decrypt(content, privateKey: wrong, kid: kid), "wrong recipient")
    }

    func testPrivateChannelKeyUnwrapAndMessage() throws {
        let policy = obj(v, "privateChannel"), pb = obj(policy, "body")
        XCTAssertTrue(try ChatCrypto.verify(policy, publicKey: obj(pb, "owner", "body", "publicKey")), "policy signature")
        let message = obj(v, "privateMessage"), mb = obj(message, "body")
        let recipient = try XCTUnwrap(obj(v, "dm", "body")["recipientId"] as? String)
        let keys = try XCTUnwrap(pb["keys"] as? [[String: Any]])
        let mine = try XCTUnwrap(keys.first { $0["participantId"] as? String == recipient })
        let kid = "channel:\(pb["id"]!):\(pb["epoch"]!):\(recipient)"
        let unwrapped = try ChatCrypto.decrypt(try XCTUnwrap(mine["jwe"] as? String), privateKey: obj(v, "recipientPrivateJwk"), kid: kid)
        XCTAssertEqual(unwrapped["key"] as? String, v["key"] as? String)

        XCTAssertTrue(try ChatCrypto.verify(message, publicKey: obj(mb, "author", "body", "publicKey")))
        let groupKey = try ChatCrypto.unbase64url(try XCTUnwrap(v["key"] as? String))
        let contentKid = "channel:\(mb["conversationId"]!):\(mb["epoch"]!):\(mb["id"]!)"
        let text = try ChatCrypto.decrypt(try XCTUnwrap(mb["content"] as? String), symmetricKey: groupKey, kid: contentKid)
        XCTAssertEqual(text["text"] as? String, "Where is Gate 2?")
        XCTAssertThrowsError(try ChatCrypto.decrypt(try XCTUnwrap(mb["content"] as? String), symmetricKey: Data(count: 32), kid: contentKid))
    }

    func testOpenChannelMessageIsSignedPlaintext() throws {
        let message = obj(v, "openMessage"), mb = obj(message, "body")
        XCTAssertTrue(try ChatCrypto.verify(obj(v, "openChannel"), publicKey: obj(v, "openChannel", "body", "owner", "body", "publicKey")))
        XCTAssertTrue(try ChatCrypto.verify(message, publicKey: obj(mb, "author", "body", "publicKey")))
        XCTAssertEqual(mb["encrypted"] as? Bool, false)
        XCTAssertEqual(mb["content"] as? String, "{\"text\":\"Where is Gate 2?\"}")
    }

    func testCanonicalJSONFollowsRFC8785() throws {
        let value: [String: Any] = ["b": 1, "a": [true, NSNull(), "x\"\\\n\u{1}é"], "\u{e9}": "z", "A": -42]
        XCTAssertEqual(String(decoding: try Canonical.data(value), as: UTF8.self),
                       "{\"A\":-42,\"a\":[true,null,\"x\\\"\\\\\\n\\u0001é\"],\"b\":1,\"é\":\"z\"}")
        XCTAssertThrowsError(try Canonical.data(["n": 1.5]))
    }
}

/// Android `ChatProtocol` rules, ported to Swift, accept the shared vectors and reject tampering.
final class ChatRulesTests: XCTestCase {
    private var v: [String: Any] = [:]
    private var now = Date()
    override func setUpWithError() throws {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().appendingPathComponent("android/app/src/test/resources/chat-vectors.json")
        v = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
        now = try Instant.parse(XCTUnwrap(v["now"] as? String))
    }
    private func o(_ k: String) -> JSON { v[k] as! JSON }

    func testVectorsPassTheSameRulesAsAndroid() throws {
        try ChatRules.message(o("dm"), policy: nil, now: now)
        try ChatRules.policy(o("privateChannel"), now: now)
        try ChatRules.message(o("privateMessage"), policy: o("privateChannel"), now: now)
        try ChatRules.policy(o("openChannel"), now: now)
        try ChatRules.message(o("openMessage"), policy: o("openChannel"), now: now)
        XCTAssertTrue(ChatRules.member(o("privateChannel"), ChatRules.participant(((o("privateMessage")["body"] as! JSON)["author"] as! JSON))))
    }
    func testTamperingAndWrongContextAreRejected() throws {
        var forged = o("dm"); var body = forged["body"] as! JSON; body["sequence"] = 2; forged["body"] = body
        XCTAssertThrowsError(try ChatRules.message(forged, policy: nil, now: now))
        XCTAssertThrowsError(try ChatRules.message(o("privateMessage"), policy: o("openChannel"), now: now), "wrong channel policy")
        XCTAssertThrowsError(try ChatRules.policy(o("privateChannel"), now: now.addingTimeInterval(7 * 3600)), "expired policy")
    }
    func testEncryptionRoundTripsAndKeepsTheExactHeader() throws {
        let priv = o("recipientPrivateJwk")
        let pub: JSON = ["kty": "EC", "crv": "P-256", "x": priv["x"]!, "y": priv["y"]!]
        let jwe = try ChatCrypto.encrypt(["text": "Gate 2 is closed"], publicKey: pub, kid: "dm:a:b:c")
        try ChatRules.jweHeader(jwe, algorithm: "ECDH-ES", kid: "dm:a:b:c")
        XCTAssertEqual(try ChatCrypto.decrypt(jwe, privateKey: priv, kid: "dm:a:b:c")["text"] as? String, "Gate 2 is closed")
        let key = Data((0..<32).map { UInt8($0) })
        let dir = try ChatCrypto.encrypt(["text": "x"], symmetricKey: key, kid: "channel:k")
        try ChatRules.jweHeader(dir, algorithm: "dir", kid: "channel:k")
        XCTAssertEqual(try ChatCrypto.decrypt(dir, symmetricKey: key, kid: "channel:k")["text"] as? String, "x")
        XCTAssertThrowsError(try ChatCrypto.decrypt(dir, symmetricKey: Data(count: 32), kid: "channel:k"))
    }
    func testInstantsMatchJavaAndJavaScript() throws {
        let d = try Instant.parse("2026-10-07T07:04:57.123456789Z")
        XCTAssertEqual(Instant.string(d), "2026-10-07T07:04:57.123Z")
        XCTAssertEqual(try Instant.parse("2026-10-07T07:04:57Z").timeIntervalSince1970, 1791356697)
        XCTAssertThrowsError(try Instant.parse("2026-10-07 07:04:57Z"))
    }
}

/// Writes iPhone-made documents for `scripts/ios-interop.mjs`, which checks them with @saathi/protocol.
final class InteropExportTests: XCTestCase {
    func testExportDocumentsForTypeScriptValidation() throws {
        guard let out = ProcessInfo.processInfo.environment["SWARM_INTEROP_OUT"] else { throw XCTSkip("Set SWARM_INTEROP_OUT to export.") }
        let me = ChatIdentity(), peer = ChatIdentity()
        let profile = try ChatDocuments.profile(me, name: "iPhone Rohan"), peerProfile = try ChatDocuments.profile(peer, name: "Android peer")
        let conversation = try ChatCrypto.directConversationID(me.participantID, peer.participantID)
        let dm = try ChatDocuments.message(me, profile: profile, conversationID: conversation, recipient: peerProfile, sequence: 1,
                                           payload: ["text": "Water at Gate 2 ✅ — पानी"], format: "TEXT")
        let receipt = try ChatDocuments.receipt(peer, profile: peerProfile, for: dm, status: "DELIVERED")
        let join = try ChatDocuments.join(me, profile: profile, channelID: UUID().uuidString.lowercased(), action: "JOIN")
        // Groups: an invite-only channel owned by this iPhone with the peer as a member, an admin action, invitations.
        let now = Date()
        let members: [JSON] = [["profile": profile, "role": "OWNER", "joinedAt": Instant.string(now), "removedAt": NSNull()],
                               ["profile": peerProfile, "role": "MEMBER", "joinedAt": Instant.string(now), "removedAt": NSNull()]]
        let policy = try ChatDocuments.policy(me, profile: profile, previous: nil, name: "Core team", visibility: "INVITE", members: members,
                                              settings: ["mode": "DISCUSSION", "admission": "INVITE_AUTO"])
        let channelKey = try XCTUnwrap(try ChatDocuments.channelKey(policy: policy, me: peer))
        let post = try ChatDocuments.message(me, profile: profile, conversationID: (policy["body"] as! JSON)["id"] as! String, policy: policy,
                                             channelKey: channelKey, sequence: 1, payload: ["text": "Briefing at 4"], format: "TEXT")
        let action = try ChatDocuments.action(me, profile: profile, policy: policy, action: "SET_ROLE", target: peer.participantID, role: "ADMIN")
        try ChatRules.action(action, policy: policy)
        let invite = try ChatDocuments.invite(me, policy: policy, recipient: peer.participantID)
        let link = try ChatDocuments.encodeInvite(invite)
        XCTAssertEqual(try ChatCrypto.sha256Hex(Canonical.data(ChatDocuments.decodeInvite(link))), try ChatCrypto.sha256Hex(Canonical.data(invite)))
        let admission = try ChatDocuments.admission(me, profile: profile, policy: try ChatDocuments.policy(me, profile: profile, previous: policy,
            name: "Core team", visibility: "INVITE", members: members, settings: ["mode": "DISCUSSION", "admission": "INVITE_PLUS_APPROVAL"]), recipient: peer.participantID)
        // Reply, forward and delete-for-everyone travel inside the encrypted DM payload.
        let dmID = (dm["body"] as! JSON)["id"] as! String
        let reply = try ChatDocuments.message(me, profile: profile, conversationID: conversation, recipient: peerProfile, sequence: 2,
                                              payload: ["text": "On my way", "replyTo": dmID, "forwarded": true], format: "TEXT")
        let deletion = try ChatDocuments.message(me, profile: profile, conversationID: conversation, recipient: peerProfile, sequence: 3,
                                                 payload: ["deletes": dmID], format: "SYSTEM")
        let doc: JSON = ["profile": profile, "peerProfile": peerProfile, "dm": dm, "reply": reply, "deletion": deletion, "receipt": receipt, "join": join,
                         "peerEncryptionPrivateJwk": peer.encryptionPrivateJWK, "policy": policy, "post": post, "action": action,
                         "invite": invite, "admission": admission, "channelKey": ChatCrypto.base64url(channelKey)]
        try JSONSerialization.data(withJSONObject: doc).write(to: URL(fileURLWithPath: out))
    }
}

final class AttachmentTests: XCTestCase {
    func testV1AndV2DecryptAndRejectTampering() throws {
        let key = Data((0..<32).map { UInt8($0 * 7 % 256) }), id = UUID().uuidString.lowercased()
        for size in [1, 1000, 65536, 65537, 200_000] {
            let plain = Data((0..<size).map { UInt8(truncatingIfNeeded: $0 &* 31 &+ 7) }), hash = ChatCrypto.sha256Hex(plain)
            let v1 = try AttachmentCrypto.encryptV1(plain, key: key, id: id)
            XCTAssertEqual(v1.count, size + 28)
            XCTAssertEqual(try AttachmentCrypto.decrypt(v1, key: key, id: id, plainSize: size, plainHash: hash), plain)
            let v2 = try AttachmentCrypto.encryptV2(plain, key: key, id: id)
            XCTAssertEqual(v2.count, size + 8 + 16 * max(1, (size + 65535) / 65536))
            XCTAssertEqual(try AttachmentCrypto.decrypt(v2, key: key, id: id, plainSize: size, plainHash: hash), plain)
            var bad = v1; bad[bad.count - 1] ^= 1
            XCTAssertThrowsError(try AttachmentCrypto.decrypt(bad, key: key, id: id, plainSize: size, plainHash: hash))
            XCTAssertThrowsError(try AttachmentCrypto.decrypt(v2, key: key, id: "other", plainSize: size, plainHash: hash), "wrong id")
        }
    }
    func testManifestBindsTheSignedMessage() throws {
        let me = ChatIdentity(), peer = ChatIdentity()
        let profile = try ChatDocuments.profile(me, name: "A"), peerProfile = try ChatDocuments.profile(peer, name: "B")
        let conversation = try ChatCrypto.directConversationID(me.participantID, peer.participantID)
        let plain = Data(repeating: 9, count: 500), key = Data(repeating: 1, count: 32), id = UUID().uuidString.lowercased()
        let cipher = try AttachmentCrypto.encryptV1(plain, key: key, id: id)
        let attachment: JSON = ["id": id, "name": "photo.jpg", "mime": "image/jpeg", "size": plain.count, "hash": ChatCrypto.sha256Hex(plain),
                                "cipherHash": ChatCrypto.sha256Hex(cipher), "key": ChatCrypto.base64url(key)]
        let envelope = try ChatDocuments.message(me, profile: profile, conversationID: conversation, recipient: peerProfile, sequence: 1,
                                                 payload: ["attachment": attachment], format: "PHOTO")
        let messageID = (envelope["body"] as! JSON)["id"] as! String
        let manifest = try ChatDocuments.attachmentManifest(me, profile: profile, envelope: envelope, attachmentID: id, cipherSize: cipher.count,
                                                            cipherHash: ChatCrypto.sha256Hex(cipher))
        try ChatRules.attachmentManifest(manifest, envelope: envelope, attachment: attachment, messageID: messageID)
        XCTAssertThrowsError(try ChatRules.attachmentManifest(manifest, envelope: envelope, attachment: attachment, messageID: UUID().uuidString.lowercased()))
    }
}
