import CryptoKit
import XCTest
@testable import SwarmCore

/// Qualifies the Swift chat crypto against the vectors Android's ChatProtocolTest uses
/// (generated by the TypeScript client): same file, same expectations.
final class ChatVectorsTests: XCTestCase {
    private var v: [String: Any] = [:]
    override func setUpWithError() throws {
        let url = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
            .deletingLastPathComponent().appendingPathComponent("android/app/src/test/resources/chat-vectors.json")
        v = try XCTUnwrap(JSONSerialization.jsonObject(with: Data(contentsOf: url)) as? [String: Any])
    }
    private func obj(_ o: Any?, _ path: String...) -> [String: Any] {
        path.reduce(o as? [String: Any] ?? [:]) { ($0[$1] as? [String: Any]) ?? [:] }
    }

    func testProfilesSignaturesAndIdentitiesMatchTheOtherClients() throws {
        let dm = obj(v, "dm"), body = obj(dm, "body"), author = obj(body, "author")
        let key = obj(author, "body", "publicKey")
        XCTAssertTrue(try ChatCrypto.verify(author, publicKey: key), "profile signature")
        XCTAssertEqual(try ChatCrypto.participantID(key), obj(author, "body")["id"] as? String)
        XCTAssertTrue(try ChatCrypto.verify(dm, publicKey: key), "DM envelope signature over canonical JSON")
        var forged = author
        var forgedBody = obj(author, "body"); forgedBody["name"] = "Impersonator"; forged["body"] = forgedBody
        XCTAssertFalse(try ChatCrypto.verify(forged, publicKey: key))
        let me = try XCTUnwrap(body["recipientId"] as? String), them = try ChatCrypto.participantID(key)
        XCTAssertEqual(try ChatCrypto.directConversationID(me, them), body["conversationId"] as? String)
    }

    func testDirectMessageDecryptsOnlyInItsContext() throws {
        let body = obj(v, "dm", "body"), privateKey = obj(v, "recipientPrivateJwk")
        let content = try XCTUnwrap(body["content"] as? String)
        let kid = "dm:\(body["conversationId"]!):\(body["id"]!):\(body["recipientId"]!)"
        XCTAssertEqual(try ChatCrypto.decrypt(content, privateKey: privateKey, kid: kid)["text"] as? String, "Where is Gate 2?")
        XCTAssertThrowsError(try ChatCrypto.decrypt(content, privateKey: privateKey, kid: kid + "x"), "wrong context")
        var parts = content.split(separator: ".").map(String.init)
        parts[3] = (parts[3].first == "A" ? "B" : "A") + parts[3].dropFirst()
        XCTAssertThrowsError(try ChatCrypto.decrypt(parts.joined(separator: "."), privateKey: privateKey, kid: kid), "tampered")
        let other = P256.KeyAgreement.PrivateKey()
        let x963 = other.publicKey.x963Representation
        let wrong: [String: Any] = ["kty": "EC", "crv": "P-256", "x": ChatCrypto.base64url(x963[1..<33]),
                                    "y": ChatCrypto.base64url(x963[33..<65]), "d": ChatCrypto.base64url(other.rawRepresentation)]
        XCTAssertThrowsError(try ChatCrypto.decrypt(content, privateKey: wrong, kid: kid), "wrong recipient")
    }

    func testPrivateChannelKeyUnwrapAndMessage() throws {
        let policy = obj(v, "privateChannel"), pb = obj(policy, "body")
        XCTAssertTrue(try ChatCrypto.verify(policy, publicKey: obj(pb, "owner", "body", "publicKey")), "policy signature")
        let message = obj(v, "privateMessage"), mb = obj(message, "body")
        let recipient = try XCTUnwrap(obj(v, "dm", "body")["recipientId"] as? String)
        let keys = try XCTUnwrap(pb["keys"] as? [[String: Any]])
        let mine = try XCTUnwrap(keys.first { $0["participantId"] as? String == recipient })
        let kid = "channel:\(pb["id"]!):\(pb["epoch"]!):\(recipient)"
        let unwrapped = try ChatCrypto.decrypt(try XCTUnwrap(mine["jwe"] as? String), privateKey: obj(v, "recipientPrivateJwk"), kid: kid)
        XCTAssertEqual(unwrapped["key"] as? String, v["key"] as? String)

        XCTAssertTrue(try ChatCrypto.verify(message, publicKey: obj(mb, "author", "body", "publicKey")))
        let groupKey = try ChatCrypto.unbase64url(try XCTUnwrap(v["key"] as? String))
        let contentKid = "channel:\(mb["conversationId"]!):\(mb["epoch"]!):\(mb["id"]!)"
        let text = try ChatCrypto.decrypt(try XCTUnwrap(mb["content"] as? String), symmetricKey: groupKey, kid: contentKid)
        XCTAssertEqual(text["text"] as? String, "Where is Gate 2?")
        XCTAssertThrowsError(try ChatCrypto.decrypt(try XCTUnwrap(mb["content"] as? String), symmetricKey: Data(count: 32), kid: contentKid))
    }

    func testOpenChannelMessageIsSignedPlaintext() throws {
        let message = obj(v, "openMessage"), mb = obj(message, "body")
        XCTAssertTrue(try ChatCrypto.verify(obj(v, "openChannel"), publicKey: obj(v, "openChannel", "body", "owner", "body", "publicKey")))
        XCTAssertTrue(try ChatCrypto.verify(message, publicKey: obj(mb, "author", "body", "publicKey")))
        XCTAssertEqual(mb["encrypted"] as? Bool, false)
        XCTAssertEqual(mb["content"] as? String, "{\"text\":\"Where is Gate 2?\"}")
    }

    func testCanonicalJSONFollowsRFC8785() throws {
        let value: [String: Any] = ["b": 1, "a": [true, NSNull(), "x\"\\\n\u{1}é"], "\u{e9}": "z", "A": -42]
        XCTAssertEqual(String(decoding: try Canonical.data(value), as: UTF8.self),
                       "{\"A\":-42,\"a\":[true,null,\"x\\\"\\\\\\n\\u0001é\"],\"b\":1,\"é\":\"z\"}")
        XCTAssertThrowsError(try Canonical.data(["n": 1.5]))
    }
}
