ALTER TABLE "OfflineEvent" ADD COLUMN "envelope" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "OfflineEvent" ADD COLUMN "receipt" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "OfflineEvent" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'PENDING';
